Server:
  port: 8082

Spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: aman123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: Hotel-Service

eureka:
  instances:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka






